version: '3.8'
services:
  auth-service:
    build:
      context: .
      dockerfile: smartbuyhub-auth-rest/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:authdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=
      - JWT_SECRET=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
      - JWT_EXPIRATION=86400000 