openapi: 3.0.3
info:
  title: SmartBuyHub Authentication API
  description: Authentication API for SmartBuyHub
  version: 1.0.0

paths:
  /api/auth/signin:
    post:
      tags:
        - Authentication
      summary: Authenticate user and generate token
      operationId: signin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Successful authentication
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JwtResponse'
        '401':
          description: Authentication failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'

  /api/auth/signup:
    post:
      tags:
        - Authentication
      summary: Register a new user
      operationId: signup
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignupRequest'
      responses:
        '200':
          description: User registered successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
        '400':
          description: Invalid input or user already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'

components:
  schemas:
    LoginRequest:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
          minLength: 3
          maxLength: 20
        password:
          type: string
          minLength: 6
          maxLength: 40

    SignupRequest:
      type: object
      required:
        - username
        - email
        - password
      properties:
        username:
          type: string
          minLength: 3
          maxLength: 20
        email:
          type: string
          format: email
          maxLength: 50
        password:
          type: string
          minLength: 6
          maxLength: 40
        roles:
          type: array
          items:
            type: string
            enum: [user, admin]

    JwtResponse:
      type: object
      properties:
        token:
          type: string
        type:
          type: string
          default: Bearer
        id:
          type: integer
          format: int64
        username:
          type: string
        email:
          type: string
        roles:
          type: array
          items:
            type: string

    MessageResponse:
      type: object
      properties:
        message:
          type: string 