openapi: 3.0.3
info:
  title: Chat Service API
  version: 1.0.0
paths:
  /v1/chat/completions:
    post:
      tags: [Chat]
      summary: Create a chat completion via Databricks/OpenAI backend
      operationId: createChatCompletion
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatCompletionRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatCompletionResponse'
components:
  schemas:
    Message:
      type: object
      properties:
        role:
          type: string
          enum: [system, user, assistant, tool]
        content:
          type: string
      required: [role, content]
    ChatCompletionRequest:
      type: object
      properties:
        model:
          type: string
        messages:
          type: array
          items:
            $ref: '#/components/schemas/Message'
        temperature:
          type: number
          format: double
          default: 1.0
        max_tokens:
          type: integer
          minimum: 1
          maximum: 4096
      required: [model, messages]
    Choice:
      type: object
      properties:
        index: { type: integer }
        message: { $ref: '#/components/schemas/Message' }
    ChatCompletionResponse:
      type: object
      properties:
        id: { type: string }
        created: { type: integer, format: int64 }
        choices:
          type: array
          items: { $ref: '#/components/schemas/Choice' }
