global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: 'localhost:8080'
#remote_write:
#  - url: https://prometheus-prod-10-prod-us-central-0.grafana.net/api/prom/push
#    basic_auth:
#      username: <your-grafana-cloud-prometheus-user-id>
#      password: <your-prometheus-api-key>