  name: build and deploy smartbuyhub-catalog
  on:
    push:
      branches:
        - main
      paths:
        - 'smartbuyhub-catalog-rest/**'
    workflow_dispatch:

  jobs:
    build-deploy:
      name: build and deploy smartbuyhub-catalog-rest
      runs-on: ubuntu-22.04
      steps:
        - name: checkout code
          uses: actions/checkout@v3

        - name: setup jdk 17
          uses: actions/setup-java@v3
          with:
            distribution: 'corretto'
            java-version: 17

        - name: unit tests
#          run: mvn -B test --file pom.xml
          run: mvn clean verify

        - name: SonarQube Scan
          run: |
            mvn sonar:sonar \
              -Dsonar.projectKey=imranaliafzal_smartbuy-hub \
              -Dsonar.projectName="SmartBuyHub Catalog REST" \
              -Dsonar.host.url=${{ secrets.SONARQUBE_HOST }} \
              -Dsonar.login=${{ secrets.SONARQUBE_TOKEN }} \
              -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

#        - name: SonarQube Scan
#          uses: kitabisa/sonarqube-action@v1.2.0
#          env:
#            SONAR_SCANNER_OPTS: -X
#          with:
#            host: ${{ secrets.SONARQUBE_HOST }}
#            login: ${{ secrets.SONARQUBE_TOKEN }}
#            projectBaseDir: "src/"
#            projectKey: "imranaliafzal_smartbuy-hub"
#            coverage:
#              jacoco:
#                xmlReportPaths: target/site/jacoco/jacoco.xml

        - name: build the app
          run: |
            mvn clean
            mvn -B package --file pom.xml

        - name: build the docker image
          uses: docker/build-push-action@v4
          with:
            context: ./smartbuyhub-catalog-rest
            push: false
            tags: ${{ secrets.DOCKER_HUB_USERNAME }}/smarthub-catalog-rest:latest

        - name: login to docker hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

        - name: List Dockerfile location
          run: ls -l ./smartbuyhub-catalog-rest

        - name: push the docker image to docker hub
          uses: docker/build-push-action@v4
          with:
            context: ./smartbuyhub-catalog-rest
            push: true
            tags: ${{ secrets.DOCKER_HUB_USERNAME }}/smarthub-catalog-rest:latest

        - name: Trigger Render deploy
          run: |
            curl https://api.render.com/deploy/srv-d1pcsg2dbo4c738avhug?key=OEsKYttUSwk