  name: build and deploy smartbuyhub-catalog
  on:
    push:
      branches:
        - main
      paths:
        - 'smartbuy-hub/smartbuyhub-catalog-rest/**'
    workflow_dispatch:

  jobs:
    build-deploy:
      name: build and deploy smartbuyhub-catalog-rest
      runs-on: ubuntu-22.04
      steps:
        - name: checkout code
          uses: actions/checkout@v3

        - name: setup jdk 17
          uses: actions/setup-java@v3
          with:
            distribution: 'corretto'
            java-version: 17

        - name: unit tests
          run: mvn -B test --file pom.xml
        
        - name: SonarQube Scan
          uses: kitabisa/sonarqube-action@v1.2.0
          env:
            SONAR_SCANNER_OPTS: -X
          with:
            host: ${{ secrets.SONARQUBE_HOST }}
            login: ${{ secrets.SONARQUBE_TOKEN }}
            projectBaseDir: "src/"
            projectKey: "imranaliafzal_smartbuy-hub"
          
         
        - name: build the app
          run: |
            mvn clean
            mvn -B package --file pom.xml

        - name: build the docker image
          uses: docker/build-push-action@v4
          with:
            context: .
            dockerfile: Dockerfile
            push: false
            tags: ${{ secrets.DOCKER_HUB_USERNAME }}/smarthub-catalog-rest:v1.0.0

        - name: login to docker hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

        - name: push the docker image to docker hub
          uses: docker/build-push-action@v4
          with:
            context: .
            dockerfile: Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_HUB_USERNAME }}/smarthub-catalog-rest:v1.0.0

